using System.ComponentModel.DataAnnotations;

namespace Syntra.FXTGroepsWerk2025.API.Models
{
    /// <summary>
    /// Data Transfer Object for Book.
    /// 
    /// Used to transfer book data between client and server.
    /// This DTO defines only the properties necessary for API input/output.
    /// 
    /// When used as a parameter in a POST or PUT action method,
    /// the [FromBody] attribute should be applied on the parameter to
    /// specify that the data is bound from the request body (typically JSON).
    /// </summary>
    public class BookDto
    {
        /// <summary>
        /// The unique identifier of the book.
        /// Optional in POST (usually generated by the database).
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Title of the book. Required.
        /// </summary>
        [Required(ErrorMessage = "Title is required.")]
        public string Title { get; set; }

        /// <summary>
        /// Number of pages in the book. Must be between 1 and 10000.
        /// </summary>
        [Range(1, 10000, ErrorMessage = "Pages must be between 1 and 10000.")]
        public int Pages { get; set; }

        /// <summary>
        /// Indicates whether the book has been read.
        /// </summary>
        public bool IsRead { get; set; }
    }
}
